from __future__ import annotations

from pathlib import Path
import sys


def test_validate_ui_pdf_viewer_layout_acceptance() -> None:
    original_argv = sys.argv[:]
    repository_root = next(parent for parent in Path(__file__).resolve().parents if (parent / 'pyproject.toml').is_file())
    try:
        sys.argv = [str(Path(__file__)), str(repository_root)]
        source = '\nimport sys\n\nrepo_root = sys.argv[1]\nif repo_root not in sys.path:\n    sys.path.insert(0, repo_root)\n\nfrom app.platform.ui_corpus import (  # noqa: E402\n    CorpusPdfDocument,\n    CorpusPdfScreenState,\n    ui_get_response,\n)\n\n\ndef assert_equal(actual: object, expected: object, message: str) -> None:\n    if actual != expected:\n        raise AssertionError(f"{message} Valeur obtenue: {actual!r}")\n\n\ndef assert_contains(text: str, expected: str, message: str) -> None:\n    if expected not in text:\n        raise AssertionError(f"{message} Texte obtenu: {text!r}")\n\n\ndef assert_not_contains(text: str, forbidden: str, message: str) -> None:\n    if forbidden in text:\n        raise AssertionError(f"{message} Texte obtenu: {text!r}")\n\n\ndocument = CorpusPdfDocument(\n    document_id="DOC-M013-VIEWER-0001",\n    title="_OceanofPDF.com_Markets_and_Momentum_-_James_F_Dalton",\n    source_status="REGISTERED",\n    diagnostic_status="DIAGNOSTIC_NOT_REQUESTED",\n    conversion_status="CONVERSION_NOT_REQUESTED",\n    canonical_version_id=None,\n    projection_status="PROJECTION_NOT_REQUESTED",\n    conversion_action_available=False,\n    selected=False,\n)\nstate = CorpusPdfScreenState(\n    documents=(document,),\n    active_selected_document_ids=(),\n    read_model_status="READ_MODEL_READY",\n)\n\n# Given un utilisateur ouvre le visualiseur PDF depuis le corpus.\n# When le PDF est rendu dans la page locale.\n# Then le cadre de visualisation occupe l\'espace utile de la fenetre au lieu de rester a la taille iframe par defaut.\nstatus_code, content_type, body = ui_get_response(\n    path="/ui/documents/DOC-M013-VIEWER-0001/pdf",\n    state=state,\n)\nassert_equal(status_code, 200, "Le visualiseur PDF doit etre servi.")\nassert_equal(content_type, "text/html; charset=utf-8", "Le visualiseur doit etre HTML.")\nassert_contains(body, \'class="pdf-viewer-page"\', "La page doit porter le layout du visualiseur.")\nassert_contains(body, \'class="pdf-viewer-frame"\', "L\'iframe PDF doit porter une classe de layout stable.")\nassert_contains(body, "height: calc(100vh - 132px);", "L\'iframe doit utiliser la hauteur disponible.")\nassert_contains(body, "min-height: 640px;", "L\'iframe doit rester lisible sur grand ecran.")\nassert_contains(body, "width: 100%;", "L\'iframe doit utiliser toute la largeur disponible.")\nassert_contains(body, "border: 0;", "Le cadre navigateur ne doit pas reduire la surface utile.")\nassert_contains(body, \'type="application/pdf"\', "Le visualiseur doit declarer le type PDF.")\nassert_not_contains(body, "<iframe title=\\"PDF original\\" src=\\"/ui/documents/DOC-M013-VIEWER-0001/pdf/content\\"></iframe>", "Le rendu ne doit plus utiliser l\'iframe sans dimension.")\n\nprint("Test d\'acceptation layout visualiseur PDF UI: OK")'
        namespace = {'__name__': __name__, '__file__': str(Path(__file__))}
        exec(compile(source, str(Path(__file__)), 'exec'), namespace)
    finally:
        sys.argv = original_argv
